### ISSUE TITLE
Training log for the pretrain stage

### ISSUE THREAD

**Issue by tgxs002** [zengyan-97/X-VLM#12]
Hi,

Thank you for releasing the code! It's an interesting project!

I'd like to know is it available to also release the pretraining logs? Or some milestones to verify the training process?

Thanks!
Blakey

**Comment by zengyan-97** [comment]
Hi, 

I find that I didn't keep the logs for X-VLM 4M or 16M...
However, recently I have trained a X-VLM model with clip-vit-base backbone on 4M data for some purpose. Generally, the performance is slightly worse than X-VLM(4M). Hope it can help. 

Here is the pre-training log: 
{"train_loss_itc": "3.29523", "train_loss_itm": "0.55888", "train_loss_mlm": "2.58581", "train_loss_bbox": "0.52016", "train_loss_giou": "0.72539", "train_lr": "0.00007", "train_lr_large": "0.00015", "epoch": 0}
{"train_loss_itc": "2.73107", "train_loss_itm": "0.49588", "train_loss_mlm": "2.01296", "train_loss_bbox": "0.46745", "train_loss_giou": "0.67073", "train_lr": "0.00009", "train_lr_large": "0.00017", "epoch": 1}
{"train_loss_itc": "2.46065", "train_loss_itm": "0.46258", "train_loss_mlm": "1.79183", "train_loss_bbox": "0.44403", "train_loss_giou": "0.64497", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 2}
{"train_loss_itc": "2.29142", "train_loss_itm": "0.44120", "train_loss_mlm": "1.66804", "train_loss_bbox": "0.42933", "train_loss_giou": "0.62842", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 3}
{"train_loss_itc": "2.16995", "train_loss_itm": "0.42518", "train_loss_mlm": "1.58681", "train_loss_bbox": "0.41858", "train_loss_giou": "0.61634", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 4}
{"train_loss_itc": "2.07655", "train_loss_itm": "0.41273", "train_loss_mlm": "1.52846", "train_loss_bbox": "0.41054", "train_loss_giou": "0.60709", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 5}
{"train_loss_itc": "2.00103", "train_loss_itm": "0.40236", "train_loss_mlm": "1.48290", "train_loss_bbox": "0.40406", "train_loss_giou": "0.59956", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 6}
{"train_loss_itc": "1.93777", "train_loss_itm": "0.39367", "train_loss_mlm": "1.44677", "train_loss_bbox": "0.39871", "train_loss_giou": "0.59330", "train_lr": "0.00009", "train_lr_large": "0.00018", "epoch": 7}
{"train_loss_itc": "1.88349", "train_loss_itm": "0.38597", "train_loss_mlm": "1.41655", "train_loss_bbox": "0.39400", "train_loss_giou": "0.58784", "train_lr": "0.00009", "train_lr_large": "0.00017", "epoch": 8}
{"train_loss_itc": "1.83591", "train_loss_itm": "0.37928", "train_loss_mlm": "1.39110", "train_loss_bbox": "0.38987", "train_loss_giou": "0.58299", "train_lr": "0.00009", "train_lr_large": "0.00017", "epoch": 9}
{"train_loss_itc": "1.79404", "train_loss_itm": "0.37330", "train_loss_mlm": "1.36903", "train_loss_bbox": "0.38629", "train_loss_giou": "0.57869", "train_lr": "0.00009", "train_lr_large": "0.00017", "epoch": 10}
{"train_loss_itc": "1.75583", "train_loss_itm": "0.36768", "train_loss_mlm": "1.34949", "train_loss_bbox": "0.38294", "train_loss_giou": "0.57475", "train_lr": "0.00008", "train_lr_large": "0.00017", "epoch": 11}
{"train_loss_itc": "1.72102", "train_loss_itm": "0.36264", "train_loss_mlm": "1.33198", "train_loss_bbox": "0.37986", "train_loss_giou": "0.57105", "train_lr": "0.00008", "train_lr_large": "0.00017", "epoch": 12}
{"train_loss_itc": "1.68896", "train_loss_itm": "0.35793", "train_loss_mlm": "1.31622", "train_loss_bbox": "0.37710", "train_loss_giou": "0.56769", "train_lr": "0.00008", "train_lr_large": "0.00016", "epoch": 13}
{"train_loss_itc": "1.65957", "train_loss_itm": "0.35345", "train_loss_mlm": "1.30173", "train_loss_bbox": "0.37451", "train_loss_giou": "0.56453", "train_lr": "0.00008", "train_lr_large": "0.00016", "epoch": 14}
{"train_loss_itc": "1.63206", "train_loss_itm": "0.34929", "train_loss_mlm": "1.28866", "train_loss_bbox": "0.37215", "train_loss_giou": "0.56163", "train_lr": "0.00008", "train_lr_large": "0.00016", "epoch": 15}
{"train_loss_itc": "1.60653", "train_loss_itm": "0.34552", "train_loss_mlm": "1.27680", "train_loss_bbox": "0.36991", "train_loss_giou": "0.55887", "train_lr": "0.00008", "train_lr_large": "0.00016", "epoch": 16}
{"train_loss_itc": "1.58254", "train_loss_itm": "0.34191", "train_loss_mlm": "1.26561", "train_loss_bbox": "0.36779", "train_loss_giou": "0.55629", "train_lr": "0.00008", "train_lr_large": "0.00016", "epoch": 17}
{"train_loss_itc": "1.55970", "train_loss_itm": "0.33848", "train_loss_mlm": "1.25507", "train_loss_bbox": "0.36580", "train_loss_giou": "0.55381", "train_lr": "0.00008", "train_lr_large": "0.00015", "epoch": 18}
{"train_loss_itc": "1.53821", "train_loss_itm": "0.33518", "train_loss_mlm": "1.24499", "train_loss_bbox": "0.36392", "train_loss_giou": "0.55150", "train_lr": "0.00008", "train_lr_large": "0.00015", "epoch": 19}
{"train_loss_itc": "1.51759", "train_loss_itm": "0.33203", "train_loss_mlm": "1.23553", "train_loss_bbox": "0.36214", "train_loss_giou": "0.54930", "train_lr": "0.00007", "train_lr_large": "0.00015", "epoch": 20}
{"train_loss_itc": "1.49807", "train_loss_itm": "0.32890", "train_loss_mlm": "1.22638", "train_loss_bbox": "0.36045", "train_loss_giou": "0.54719", "train_lr": "0.00007", "train_lr_large": "0.00015", "epoch": 21}
{"train_loss_itc": "1.47934", "train_loss_itm": "0.32590", "train_loss_mlm": "1.21784", "train_loss_bbox": "0.35883", "train_loss_giou": "0.54519", "train_lr": "0.00007", "train_lr_large": "0.00014", "epoch": 22}
{"train_loss_itc": "1.46137", "train_loss_itm": "0.32305", "train_loss_mlm": "1.20971", "train_loss_bbox": "0.35724", "train_loss_giou": "0.54322", "train_lr": "0.00007", "train_lr_large": "0.00014", "epoch": 23}
{"train_loss_itc": "1.44407", "train_loss_itm": "0.32028", "train_loss_mlm": "1.20188", "train_loss_bbox": "0.35572", "train_loss_giou": "0.54134", "train_lr": "0.00007", "train_lr_large": "0.00014", "epoch": 24}
{"train_loss_itc": "1.42745", "train_loss_itm": "0.31753", "train_loss_mlm": "1.19445", "train_loss_bbox": "0.35427", "train_loss_giou": "0.53956", "train_lr": "0.00007", "train_lr_large": "0.00014", "epoch": 25}
{"train_loss_itc": "1.41134", "train_loss_itm": "0.31484", "train_loss_mlm": "1.18714", "train_loss_bbox": "0.35285", "train_loss_giou": "0.53782", "train_lr": "0.00007", "train_lr_large": "0.00013", "epoch": 26}
{"train_loss_itc": "1.39579", "train_loss_itm": "0.31222", "train_loss_mlm": "1.18010", "train_loss_bbox": "0.35152", "train_loss_giou": "0.53618", "train_lr": "0.00007", "train_lr_large": "0.00013", "epoch": 27}
{"train_loss_itc": "1.38078", "train_loss_itm": "0.30967", "train_loss_mlm": "1.17329", "train_loss_bbox": "0.35020", "train_loss_giou": "0.53453", "train_lr": "0.00006", "train_lr_large": "0.00013", "epoch": 28}
{"train_loss_itc": "1.36609", "train_loss_itm": "0.30713", "train_loss_mlm": "1.16668", "train_loss_bbox": "0.34892", "train_loss_giou": "0.53295", "train_lr": "0.00006", "train_lr_large": "0.00013", "epoch": 29}
{"train_loss_itc": "1.35187", "train_loss_itm": "0.30462", "train_loss_mlm": "1.16024", "train_loss_bbox": "0.34769", "train_loss_giou": "0.53142", "train_lr": "0.00006", "train_lr_large": "0.00012", "epoch": 30}
{"train_loss_itc": "1.33789", "train_loss_itm": "0.30220", "train_loss_mlm": "1.15407", "train_loss_bbox": "0.34651", "train_loss_giou": "0.52997", "train_lr": "0.00006", "train_lr_large": "0.00012", "epoch": 31}
{"train_loss_itc": "1.32444", "train_loss_itm": "0.29986", "train_loss_mlm": "1.14798", "train_loss_bbox": "0.34533", "train_loss_giou": "0.52851", "train_lr": "0.00006", "train_lr_large": "0.00012", "epoch": 32}
{"train_loss_itc": "1.31131", "train_loss_itm": "0.29754", "train_loss_mlm": "1.14205", "train_loss_bbox": "0.34417", "train_loss_giou": "0.52708", "train_lr": "0.00006", "train_lr_large": "0.00012", "epoch": 33}
{"train_loss_itc": "1.29844", "train_loss_itm": "0.29522", "train_loss_mlm": "1.13620", "train_loss_bbox": "0.34302", "train_loss_giou": "0.52567", "train_lr": "0.00006", "train_lr_large": "0.00011", "epoch": 34}
{"train_loss_itc": "1.28595", "train_loss_itm": "0.29297", "train_loss_mlm": "1.13056", "train_loss_bbox": "0.34191", "train_loss_giou": "0.52431", "train_lr": "0.00006", "train_lr_large": "0.00011", "epoch": 35}
{"train_loss_itc": "1.27388", "train_loss_itm": "0.29075", "train_loss_mlm": "1.12507", "train_loss_bbox": "0.34084", "train_loss_giou": "0.52298", "train_lr": "0.00005", "train_lr_large": "0.00011", "epoch": 36}
{"train_loss_itc": "1.26206", "train_loss_itm": "0.28857", "train_loss_mlm": "1.11964", "train_loss_bbox": "0.33980", "train_loss_giou": "0.52170", "train_lr": "0.00005", "train_lr_large": "0.00011", "epoch": 37}
{"train_loss_itc": "1.25059", "train_loss_itm": "0.28644", "train_loss_mlm": "1.11436", "train_loss_bbox": "0.33876", "train_loss_giou": "0.52043", "train_lr": "0.00005", "train_lr_large": "0.00010", "epoch": 38}
{"train_loss_itc": "1.23946", "train_loss_itm": "0.28431", "train_loss_mlm": "1.10929", "train_loss_bbox": "0.33775", "train_loss_giou": "0.51916", "train_lr": "0.00005", "train_lr_large": "0.00010", "epoch": 39}
{"train_loss_itc": "1.22863", "train_loss_itm": "0.28226", "train_loss_mlm": "1.10433", "train_loss_bbox": "0.33676", "train_loss_giou": "0.51792", "train_lr": "0.00005", "train_lr_large": "0.00010", "epoch": 40}

**Comment by tgxs002** [comment]
Many thanks!
