### ISSUE TITLE
Script to generate RegionTextJsonDataset?

### ISSUE THREAD

**Issue by daizuozhuo** [zengyan-97/X-VLM#13]
HI, I understand that the data cannot redistributed, but could you share the code to generate RegionTextJsonDataset from the official COCO, VG datasets so we can follow the pretraining method?

**Comment by zengyan-97** [comment]
Hi, 

I found that some other methods just released their data. 
So, I will release the processed json files (image not included) in this week. 
Please follow up then.

**Comment by xugy16** [comment]
Is the json file avaiable now?

**Comment by mariyahendriksen** [comment]
yes, I am also interested! :)

**Comment by zengyan-97** [comment]
Hi, 

The json files have been available for a while. Please see README for details. 
On the other hand, only some preprocessing to filter invalid bboxes in the public data. You can download the data from the original websites, and do the filtering by yourself.
