### ISSUE TITLE
Performance of different vision encoders

### ISSUE THREAD

**Issue by AI-in-Health** [zengyan-97/X-VLM#18]
Thanks for your great sharing.

https://github.com/zengyan-97/X-VLM/blob/e7b960256d194952321b5adad39770c03e6ce9c2/models/xvlm.py#L121

As shown above, you mentioned in the code that initilaizing the vision encoder with deit is worser than clip-vit and swin. 

Do you have some supporting results? For example, the performance on Image-Text Retrieval with deit or swin

**Comment by zengyan-97** [comment]
Hi, 

Sorry for my late rely. 

Yes, i tried. deit is the worst. But I can't find my preliminary experiment results. 
FYI, clip-vit-base performs similarly to swin-base or beit2-vit-base. beit2-vit-large is better than swin-large.
