### ISSUE TITLE
About batch sampling `iter_perc`

### ISSUE THREAD

**Issue by yangbang18** [zengyan-97/X-VLM#19]
Thanks for your code.

I note that in your paper, you said "We sample the data by making half of the images in a batch containing bounding box annotations".

But the code is:
https://github.com/zengyan-97/X-VLM/blob/e7b960256d194952321b5adad39770c03e6ce9c2/Pretrain.py#L82-L121

The `iter_perc` you used is 0.5, which means only 50% of time, the model takes a batch of image-text-box data and a batch of image-text data as input; and otherwise, the model only takes a batch of image-text data as input.

Therefore, it seems that `iter_perc = 1.0` fits your statement in the paper.

According to the ablation study results in Table 4, you have certainly tested the impact of `iter_perc = 0.0` (corresponding to the model, X-VLM w/o all).

So, have you tested more values of `iter_perc` (e.g., 1.0)?

**Comment by zengyan-97** [comment]
Hi, 

Sorry for my late reply. 
I used iter_perc = 1.0. (or at least I used iter_perc = 1.0 in X2-VLM...)
I don't remember clearly.
