### ISSUE TITLE
NLVR Pretrain

### ISSUE THREAD

**Issue by lonestar234028** [zengyan-97/X-VLM#21]
Hi @zengyan-97:
For NLVR pretraining, how did you do it? Sorry I can not found it in your paper.

**Comment by zengyan-97** [comment]
https://github.com/zengyan-97/X-VLM/blob/master/models/model_nlvr_pretrain.py

ps: we re-implement NLVR2 in X2-VLM following VLMo/BEiT-3 (no NLVR pre-training anymore, and achieving better performance)
