### ISSUE TITLE
Hello, please ask the train_files in configs/yaml file to "hdfs: // path / to / vg" error, please change how to set up

### ISSUE THREAD

**Issue by zhanghehe8** [zengyan-97/X-VLM#3]
Hello, please ask the train_files in configs/yaml file to "hdfs: // path / to / vg" error, please change how to set up

**Comment by zengyan-97** [comment]
Please prepare your data and replace it with the path to visual genome dataset. I am not sure if I get your question.

**Comment by zhanghehe8** [comment]
Thank you for your reply, can you provide the right JSON Files?The JSON file in the link cannot be used in RegionTextJsondataSet processing.

> Please prepare your data and replace it with the path to visual genome dataset. I am not sure if I get your question.

Thank you for your reply, can you provide the right JSON Files?The JSON file in the link cannot be used in RegionTextJsondataSet processing.

**Comment by zhanghehe8** [comment]
When making region_dataset, since there is no suitable JSON files, the JSON file you provide does not contain Box.

**Comment by zengyan-97** [comment]
Please read the README file carefully. I did not provide pre-training datasets (it might be available in March.). The JSON file I provided is for fine-tuning only.

**Comment by zhanghehe8** [comment]
I'm glad to receive your reply. I see

**Comment by tangjie010101** [comment]
> Please read the README file carefully. I did not provide pre-training datasets (it might be available in March.). The JSON file I provided is for fine-tuning only.

good job  !!   Looking forward to your pre-training datasets
