### ISSUE TITLE
Could you provide your training logs of coco caption? Thank you very much!

### ISSUE THREAD

**Issue by pypypypy666** [zengyan-97/X-VLM#6]
Could you provide your training logs of coco caption? Thank you very much!

**Comment by zengyan-97** [comment]
Hi, 
Sorry for my late reply. 

I only keep this training log of captioning based on X-VLM(16M): 
{"train_lr": "0.00001", "train_loss": "3.09465", "test_Bleu_1": 0.7888877725308794, "test_Bleu_2": 0.63571035330044, "test_Bleu_3": 0.5010730538646152, "test_Bleu_4": 0.3913670270575186, "test_METEOR": 0.30496697421985314, "test_ROUGE_L": 0.5970224740919123, "test_CIDEr": 1.317922681426818, "test_SPICE": 0.23711267501362399, "epoch": 0}
{"train_lr": "0.00001", "train_loss": "2.98785", "test_Bleu_1": 0.7908520616358936, "test_Bleu_2": 0.6381588587372502, "test_Bleu_3": 0.5034545904748693, "test_Bleu_4": 0.3940724470046297, "test_METEOR": 0.3044191834423089, "test_ROUGE_L": 0.5968370063641272, "test_CIDEr": 1.324427769391428, "test_SPICE": 0.23648371743116095, "epoch": 1}
{"train_lr": "0.00001", "train_loss": "2.95646", "test_Bleu_1": 0.7900966620445572, "test_Bleu_2": 0.6394082741826733, "test_Bleu_3": 0.5067956381747537, "test_Bleu_4": 0.3990826836166066, "test_METEOR": 0.30812466366805014, "test_ROUGE_L": 0.6003008324478327, "test_CIDEr": 1.335514654758239, "test_SPICE": 0.23785805830856616, "epoch": 2}
{"train_lr": "0.00000", "train_loss": "2.93689", "test_Bleu_1": 0.7885322668167135, "test_Bleu_2": 0.6375335548575466, "test_Bleu_3": 0.5049943737820617, "test_Bleu_4": 0.3974852071709018, "test_METEOR": 0.3076980686063203, "test_ROUGE_L": 0.5984061051446633, "test_CIDEr": 1.332406512277844, "test_SPICE": 0.23666827912166746, "epoch": 3}
{"train_lr": "0.00000", "train_loss": "2.92356", "test_Bleu_1": 0.7897854626961097, "test_Bleu_2": 0.6385248029045398, "test_Bleu_3": 0.5062238463521957, "test_Bleu_4": 0.3988569646467052, "test_METEOR": 0.30886155569362295, "test_ROUGE_L": 0.6002198552354895, "test_CIDEr": 1.3395548597453977, "test_SPICE": 0.2384228247143562, "epoch": 4}
